---
title: May the dharma progress along the path
---

The Buddhist path (_mārga_) to liberation, also referred to as awakening, is described in a wide variety of ways.

The classical one from the Theravada is the [:Eightfold Path](https://en.wikipedia.org/wiki/Noble_Eightfold_Path).

Mahāyāna Buddhism is based principally upon the path of a bodhisattva, which can be described in terms of the [:six perfections (_pāramitās_)](https://en.wikipedia.org/wiki/P%C4%81ramit%C4%81#Six_perfections) or in terms of the [:five paths](https://en.wikipedia.org/wiki/Buddhist_paths_to_liberation#Five_paths) and [:ten bhūmis](https://en.wikipedia.org/wiki/Bh%C5%ABmi_(Buddhism)). The five paths and ten bhūmis are often merged in the Mahāyāna sources. Before attaining the ten stages, the bodhisattva traverses the first two of the five Mahayana paths, that is the path of accumulation (_saṃbhāra-mārga_) and the path of preparation (_prayoga-mārga_). The classic ten stages of the bodhisattva are grouped within the three subsequent paths:

- The 1st Bhūmi corresponds to the path of seeing (_darśana-mārga_)
- Bhūmis 2 to 7 correspond to the path of cultivation (_bhāvanā-mārga_)
- Bhūmis 8 to 10 are within the path of no more learning (_aśaikṣā-mārga_)

In the Dagpo Kagyu tradition as presented by Dagpo Tashi Namgyal, Mahāmudrā is divided into four distinct phases known as the [:four yogas of mahāmudrā](https://en.wikipedia.org/wiki/Mahamudra#Practices_and_methods).



