---
title: "24 Daoist Exercises"
subtitle: As taught by the International Tai Chi Chuan Association
author: Daniel Kapitan
date: 2025-10-11
page-layout: full
---

These exercises are done as a warming up, prior to doing the actual Tai Chi form. I collated the list from the ITCCA, the videos are provided by [Tai Chi Serbia](www.youtube.com/@TaiChiSerbia).

:::: {.columns}

::: {.column width="50%"}
1. Tai Chi, Yin and Yang
2. Open and close crossed hands
3. Sea waves rippling
4. Spreading the wings left and right
5. The water mill turns
6. The rhinoceros looking at the moon
7. The golden monkey offers fruit
8. The sacred turtle paddles
9. Turning in the form of Pa Qua
10. The head of the dragon and the tail of the phoenix
11. The King of the heaven supports his back
12. The heavenly king Li holds up a pagoda
:::

::: {.column width="50%"}
13. The flying eagle turns its hcad
14. Big and small golden stars
15. The hands and feet meet
16. The rhinoceros drinks water
17. The child prays to Kwan-Yin
18. Butterflies fly in pairs
19. Exhaling old air and inhaling fresh air
20. Closing the eyes to rejuvenate the spirit
21. The holy crane stretches its claws
22. Continuously turning single whip
23. Equally beautiful
24. The Golden flowers fall softly
:::

::::

::: {.panel-tabset}
## 1-2
{{< video https://youtu.be/oWrNt4Goi9c?si=8NiUkfIJ3_Ob5uQL >}}

## 3-4
{{< video https://youtu.be/zCi9k7Da91g?si=e4zhuiElE9foyytM >}}

## 5-6
{{< video https://youtu.be/wZg3kVTaJWs?si=5ZtgSMo_ZNbQy-aN >}}

## 7-8
{{< video https://youtu.be/990_X7C-778?si=zZGGrBPSKI9ng4pp >}}

## 9-10
{{< video https://youtu.be/1wZxqFVJbJY?si=CPfT1Rrzsuvh4F3o >}}

## 11-12
{{< video https://youtu.be/6qH6uQB73s0?si=5O-k_AznwyzQrrp7 >}}

## 13-14
{{< video https://youtu.be/Qm7cIUtMpnI?si=iZUNc8ioFHYFbYex >}}

## 15-16
{{< video https://youtu.be/FeI-GiPX5bk?si=9Y9MhmVoz1OZ4SgB >}}

## 17-18
{{< video https://youtu.be/nRhgqZ250t0?si=MmcRyHYF6Jw5f9lX >}}

## 19-20
{{< video https://youtu.be/cpRM_uh4rVg?si=3foa8BN80LV6DdHk >}}

## 21-22
{{< video https://youtu.be/Wmd_7e56mck?si=imIiYn8eV5DOvJGK >}}

## 23-24
{{< video https://youtu.be/xWcnEhIyeGY?si=pGGSlbuhVshFITzg >}}
:::





 
